CREATE TABLE csv_test (track_id varchar, track_name varchar, track_artist varchar, track_popularity integer, track_album_id varchar, track_album_release_date varchar, playlist_name varchar, playlist_id varchar, playlist_genre varchar, playlist_subgenre varchar, danceability float8, energy float8, key integer, loudness float8, mode integer, speechiness float8, acousticness float8, instrumentalness float8, liveness float8, valence float8, tempo float8, duration_ms float8);
\copy (SELECT * FROM csv_test) to '/path/to/spotify_songs.csv' with CSV HEADER;
CREATE TABLE tracks (track_id varchar, track_name varchar);
INSERT INTO tracks (track_id, track_name) SELECT track_id, track_name FROM csv_test;
SELECT * FROM tracks LIMIT 10;
CREATE TABLE artists (track_id varchar, track_artist varchar, track_popularity varchar);
INSERT INTO artists (track_id, track_artist, track_popularity) SELECT track_id, track_artist, track_popularity FROM csv_test;
SELECT * FROM artists LIMIT 10; 
CREATE TABLE album (track_id varchar, track_album_id varchar, track_album_name varchar, track_album_release_date varchar);
INSERT INTO album (track_id, track_album_id, track_album_name, track_album_release_date) SELECT track_id, track_album_id, track_album_name, track_album_release_date FROM csv_test;
SELECT * FROM album LIMIT 10;
CREATE TABLE playlist (track_id varchar, playlist_id varchar, playlist_name varchar); 
INSERT INTO playlist (track_id, playlist_id, playlist_name) SELECT track_id, playlist_id, playlist_name FROM csv_test; 
SELECT * FROM playlist LIMIT 10;
CREATE TABLE genre (track_id varchar, genre varchar, subgenre varchar);
INSERT INTO genre (track_id, genre, subgenre) SELECT track_id, playlist_genre, playlist_subgenre FROM csv_test;
SELECT * FROM genre LIMIT 10;
CREATE TABLE speed_stats (track_id varchar, tempo float8, duration_ms float8);
INSERT INTO speed_stats (track_id, tempo, duration_ms) SELECT track_id, tempo, duration_ms FROM csv_test;
SELECT * FROM speed_stats LIMIT 10;
CREATE TABLE sound_stats (track_id varchar, key integer, mode integer, speech float8, acoustics float8, loudness float8, instrumentals float8);
INSERT INTO sound_stats (track_id, key, mode, speech, acoustics, loudness, instrumentals) SELECT track_id, key, mode, speechiness, acousticness,  loudness, instrumentalness FROM csv_test;
SELECT * FROM sound_stats LIMIT 10;
CREATE TABLE mood_stats (track_id varchar, energy float8, danceability float8, liveness float8, valence float8); 
INSERT INTO mood_stats (track_id, energy, danceability, liveness, valence) SELECT track_id, energy, danceability, liveness, valence FROM csv_test;  
SELECT * FROM mood_stats LIMIT 10;
